server:
  port: 8085

spring:
  keycloak:
    server-url: http://keycloak:8080
    realm: greenpulse
    client-id: greenpulseclient
    client-secret: ${KEYCLOAK_SECRET}
    admin-username: admin
    admin-password: admin
  application:
    name=user-management-service
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:greenpulse}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9095,kafka-3:9098
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-registered-events
      properties:
        spring:
          json:
            trusted: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/greenpulse